---
title: "Bayesian inference of technological phylogenies using continuous traits from the archaeological record"
authors: 
  - Ben Marwick 
  - David N. Matzig 
  - Felix Riede 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Department of Anthropology, University of Washington, Seattle, USA
2. Department of Archaeology and Heritage Studies, Aarhus University, Denmark


Abstract: The twentieth century saw two modes of thinking spread through biological systematics:  population thinking and tree thinking. Many archaeologists investigating ancient technologies have adopted the population thinking approach for archaeological systematics, as evident from the rise of work on quantifiable, attribute-based patterns of diversity in studies of past technological systems, much of it driven by application of geometric morphometrics. Yet, tree thinking, as one of the central concepts of phylogenetic biology, remains rare in the archaeological sciences. We review some of the obstacles that have impeded the uptake of this concept by archaeologists. Some of these are conceptual, but we identify one specific methodological obstacle: the prevailing use of discrete character traits in phylogenetic analysis in many fields. This is a major challenge for archaeological applications where standardised trait-analytical protocols are scarce. To address this challenge, we present a case study that demonstrates a Bayesian framework for inferring phylogenies using continuous traits derived from artefact shape coefficients obtained via outline based geometric morphometrics. We use a previously published sample of Late Neolithic/Early Bronze Age arrowheads from Northwestern Europe to demonstrate the efficacy and accessibility of our approach. We also sketch out the potential for phylogenetic comparative methods to address archaeological questions. 


## Outline

- Artefact outline data, EFA, PCA, PCs are new shape variables to describe the arteafacts
- PCs are continuous variables for input as character state data, we start with a simple model to infer phylogenies from the PC data: birth-death model, Brownian motion, strict constant clock rates, 
- We can measure the strength of correlation among sets of the characters used to infer the phylogeny, is the evolution of shape variables correlated?
- We can measure the rate of evolution in each branch of the tree, do different parts of the tree evolve at different rates? 














